### ISSUE TITLE
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fe7c6481cf0

### ISSUE THREAD

**Issue by HelloBroTan** [sysid/sse-starlette#119]
I deployed a web application developed by FastAPI and uvicorn。It can serve normally. But once I ran a test script and pressed "ctrl+C", it seems to be broken with next information when a new request posted.
###--------------------------environment requirements###
"fastapi==0.109.0
langchain-core==0.1.52
sse-starlette==1.8.2
numpy==1.26.4
modelscope==1.14.0
pandas==2.0.3
langchain
faiss-cpu==1.7.4
sentence-transformers==2.2.2
llama-index-core==0.10.55
llama-index-legacy==0.9.48
dashscope==1.19.1
apscheduler
aioredis
gunicorn
volcengine"
###--------------------------test script###
"while True:
    query = 'some simple description words about something'
    asyncio.run(chat(query))"
###--------------------------error log###
part01:
"Traceback (most recent call last):
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpx/_transports/default.py", line 271, in __aiter__
    async for part in self._httpcore_stream:
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 407, in __aiter__
    raise exc from None
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 403, in __aiter__
    async for part in self._stream:
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/http11.py", line 342, in __aiter__
    raise exc
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/http11.py", line 334, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/http11.py", line 203, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_async/http11.py", line 213, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/opt/conda/envs/agent/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
The above exception was the direct cause of the following exception:..omit omit omit....

part02:
2024-12-21 09:43:23,765 - server.api.new_list_api - INFO - -code 4 - 【【【【【search some recent news about Donald Trump】】】】】。
2024-12-21 09:43:23,765 - app - ERROR - unhandled errors in a TaskGroup (1 sub-exception)
Traceback (most recent call last):
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
  File "/opt/conda/envs/agent/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 531, in receive
    await self.message_event.wait()
  File "/opt/conda/envs/agent/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fe7c6481cf0
During handling of the above exception, another exception occurred:
  + Exception Group Traceback (most recent call last):
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/opt/conda/envs/agent/lib/python3.10/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/workspace/agentproject/server/server_api.py", line 49, in chat_iterator
    |     async for response in FUNCTIONS_MAP[code](model):
    |   File "/workspace/agentproject/server/api/new_list_api.py", line 43, in chat_new_list_detail
    |     res = news_search(query, model.tags)
    | TypeError: news_search() takes 1 positional argument but 2 were given
    +------------------------------------
"

**Comment by sysid** [comment]
This information is not helpful, it does not provide e reproducible example nor does it clearly identify a problem with sse-starlette.
